# GitHub Actions workflow for deploying a Python Flask app to Azure Web App

name: Build and Deploy Python App to Azure - testpythonflask

on:
  push:
    branches:
      - Flaskrepo  # Runs when changes are pushed to this branch
  workflow_dispatch:  # Allows manual triggering

env:
  APP_ENV: dev
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
  ZIPFILE: package.zip

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Set up Python Version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and Start Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests (e.g., PyTest)
      # - name: Run Tests
      #   run: pytest

      - name: Zip Artifact for Deployment
        run: zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "*.yml"

      - name: Upload Artifact for Deployment Jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for JWT authentication
      contents: read

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip Artifact for Deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1445CB15A781497B89E79C5719E169D1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F5F1C2D4AF1B47D89F26D0B1248D92CC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0FA76CE81D94BA49CEE36CBF5A7A403 }}
 
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'testpythonflask'
          slot-name: 'Production'
